# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-27 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20200327_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='nickname',
            new_name='owner',
        ),
    ]
