# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-05-10 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20200509_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='target',
            field=models.CharField(max_length=100, null=True, verbose_name='评论目标'),
        ),
    ]
